"""empty message

Revision ID: 0f4283b55d09
Revises: 769549423658
Create Date: 2025-04-02 10:35:54.323266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f4283b55d09'
down_revision: Union[str, None] = '769549423658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_classes_head_teacher_id', 'classes', 'users', ['head_teacher_id'], ['id'], use_alter=True)
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=50), nullable=False, comment='类型'))
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', mysql.VARCHAR(length=50), nullable=False, comment='类型'))
    op.drop_column('notifications', 'notification_type')
    op.drop_constraint('fk_classes_head_teacher_id', 'classes', type_='foreignkey')
    # ### end Alembic commands ###
