"""add-uploads-model

Revision ID: 25df4feaa9a7
Revises: f618591bbdc2
Create Date: 2025-04-21 09:02:44.326154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25df4feaa9a7'
down_revision: Union[str, None] = 'f618591bbdc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=512), nullable=False, comment='文件路径'),
    sa.Column('file_type', sa.String(length=100), nullable=False, comment='文件MIME类型'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小（字节）'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='所属模块，如ai-assistant, profile, etc.'),
    sa.Column('entity_type', sa.String(length=50), nullable=True, comment='实体类型，如message, user, etc.'),
    sa.Column('entity_id', sa.Integer(), nullable=True, comment='关联实体ID'),
    sa.Column('uploader_id', sa.Integer(), nullable=False, comment='上传者ID'),
    sa.Column('is_public', sa.Integer(), nullable=False, comment='是否公开，0-私有，1-公开'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uploads_entity_type_entity_id', 'uploads', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_uploads_id'), 'uploads', ['id'], unique=False)
    op.create_index('ix_uploads_module', 'uploads', ['module'], unique=False)
    op.create_index('ix_uploads_uploader_id', 'uploads', ['uploader_id'], unique=False)
    op.create_table('ai_file_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False, comment='消息ID'),
    sa.Column('upload_id', sa.Integer(), nullable=False, comment='上传文件ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['message_id'], ['ai_messages.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_file_attachments_id'), 'ai_file_attachments', ['id'], unique=False)
    op.create_index('ix_ai_file_attachments_message_id', 'ai_file_attachments', ['message_id'], unique=False)
    op.create_index('ix_ai_file_attachments_upload_id', 'ai_file_attachments', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_file_attachments_upload_id', table_name='ai_file_attachments')
    op.drop_index('ix_ai_file_attachments_message_id', table_name='ai_file_attachments')
    op.drop_index(op.f('ix_ai_file_attachments_id'), table_name='ai_file_attachments')
    op.drop_table('ai_file_attachments')
    op.drop_index('ix_uploads_uploader_id', table_name='uploads')
    op.drop_index('ix_uploads_module', table_name='uploads')
    op.drop_index(op.f('ix_uploads_id'), table_name='uploads')
    op.drop_index('ix_uploads_entity_type_entity_id', table_name='uploads')
    op.drop_table('uploads')
    # ### end Alembic commands ###
