"""add_quant_item_fields_and_category_model

Revision ID: b010d2fb486b
Revises: 0f4283b55d09
Create Date: 2025-04-07 23:19:37.522435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b010d2fb486b'
down_revision: Union[str, None] = '0f4283b55d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quant_item_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='分类描述'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序顺序'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_quant_item_categories_id'), 'quant_item_categories', ['id'], unique=False)
    op.add_column('quant_items', sa.Column('min_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='最小分数'))
    op.add_column('quant_items', sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='最大分数'))
    op.add_column('quant_items', sa.Column('default_reason', sa.Text(), nullable=True, comment='默认原因'))
    op.add_column('quant_items', sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False, comment='权重'))
    op.alter_column('quant_items', 'default_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               nullable=True,
               existing_comment='默认分数')
    op.alter_column('students', 'class_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='班级ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'class_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='班级ID')
    op.alter_column('quant_items', 'default_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               nullable=False,
               existing_comment='默认分数')
    op.drop_column('quant_items', 'weight')
    op.drop_column('quant_items', 'default_reason')
    op.drop_column('quant_items', 'max_score')
    op.drop_column('quant_items', 'min_score')
    op.drop_index(op.f('ix_quant_item_categories_id'), table_name='quant_item_categories')
    op.drop_table('quant_item_categories')
    # ### end Alembic commands ###
