"""Modify ai_table

Revision ID: b0f602c2b6b4
Revises: b47f9c020691
Create Date: 2025-04-15 11:36:54.182035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b0f602c2b6b4'
down_revision: Union[str, None] = 'b47f9c020691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='对话标题'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_id'), 'ai_conversations', ['id'], unique=False)
    op.create_index('ix_ai_conversations_user_id_updated_at', 'ai_conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='对话ID'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='消息角色，user或assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('processing_time', sa.Integer(), nullable=True, comment='处理时间（仅适用于assistant消息）'),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_messages_conversation_id_created_at', 'ai_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_messages_id'), 'ai_messages', ['id'], unique=False)
    op.drop_index('ix_ai_queries_id', table_name='ai_queries')
    op.drop_table('ai_queries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_queries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('query_text', mysql.TEXT(), nullable=False, comment='查询文本'),
    sa.Column('response_text', mysql.TEXT(), nullable=True, comment='响应文本'),
    sa.Column('context_data', mysql.TEXT(), nullable=True, comment='上下文数据'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('completed_at', mysql.DATETIME(), nullable=True, comment='完成时间'),
    sa.Column('processing_time', mysql.INTEGER(), autoincrement=False, nullable=True, comment='处理时间（毫秒）'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_queries_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_ai_queries_id', 'ai_queries', ['id'], unique=False)
    op.drop_index(op.f('ix_ai_messages_id'), table_name='ai_messages')
    op.drop_index('ix_ai_messages_conversation_id_created_at', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index('ix_ai_conversations_user_id_updated_at', table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
