"""update_student_model

Revision ID: b47f9c020691
Revises: bc04b360072e
Create Date: 2025-04-07 23:44:31.485229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b47f9c020691'
down_revision: Union[str, None] = 'bc04b360072e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('phone', sa.String(length=20), nullable=True, comment='电话'))
    op.add_column('students', sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'))
    op.add_column('students', sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像URL'))
    op.add_column('students', sa.Column('total_score', sa.Float(), nullable=True, comment='总分'))
    op.add_column('students', sa.Column('rank', sa.Integer(), nullable=True, comment='排名'))
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_active')
    op.drop_column('students', 'rank')
    op.drop_column('students', 'total_score')
    op.drop_column('students', 'avatar_url')
    op.drop_column('students', 'email')
    op.drop_column('students', 'phone')
    # ### end Alembic commands ###
