"""add_category_id_to_quant_item

Revision ID: bc04b360072e
Revises: b010d2fb486b
Create Date: 2025-04-07 23:26:47.992622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc04b360072e'
down_revision: Union[str, None] = 'b010d2fb486b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quant_items', sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'))
    op.create_foreign_key(None, 'quant_items', 'quant_item_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quant_items', type_='foreignkey')
    op.drop_column('quant_items', 'category_id')
    # ### end Alembic commands ###
