"""Modify_AI_conversation

Revision ID: f618591bbdc2
Revises: 16e9c9b0e885
Create Date: 2025-04-17 08:32:04.107121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f618591bbdc2'
down_revision: Union[str, None] = '16e9c9b0e885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_messages', sa.Column('use_local_model', sa.Boolean(), nullable=True, comment='是否使用本地模型'))
    op.add_column('ai_messages', sa.Column('model_name', sa.String(length=100), nullable=True, comment='使用的模型名称'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_messages', 'model_name')
    op.drop_column('ai_messages', 'use_local_model')
    # ### end Alembic commands ###
